### ISSUE TITLE
Webinterface nicht mehr erreichbar

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#179]
- **"Einstellungen"-Ordner als Zip** (Paranoide können die Downloads.db weglassen)
[RSScrawler.zip](https://github.com/rix1337/RSScrawler/files/1817257/RSScrawler.zip)

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing...
Requirement already up-to-date: cfscrape in /usr/lib/python2.7/site-packages
Requirement already up-to-date: PyExecJS>=1.4.0 in /usr/lib/python2.7/site-packages (from cfscrape)
Requirement already up-to-date: requests>=2.0.0 in /usr/lib/python2.7/site-packages (from cfscrape)
Requirement already up-to-date: six>=1.10.0 in /usr/lib/python2.7/site-packages (from PyExecJS>=1.4.0->cfscrape)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Fetching origin
HEAD is now at ef4a55e Update search.py
From https://github.com/rix1337/RSScrawler
* branch master -> FETCH_HEAD
Already up to date.
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
┌────────────────────────────────────────────────────────┐
Programminfo: RSScrawler v.4.0.7 von RiX
Projektseite: https://github.com/rix1337/RSScrawler
└────────────────────────────────────────────────────────┘
Docker-Modus: JDownloader-Pfad und Port können nur per Docker-Run angepasst werden!
Nutze das "folderwatch" Unterverzeichnis von "/jd2" für Crawljobs
Der Webserver ist erreichbar unter http://192.168.1.34:9090
Drücke [Strg] + [C] zum Beenden
2018-03-15 22:53:44 - Alle Suchfunktion gestartet.
2018-03-15 22:54:56 - Alle Suchfunktion ausgeführt (Dauer: 1.2 Minuten)!
----------------------------------------
Exception happened during processing of request from ('192.168.1.201', 55377)
Traceback (most recent call last):
File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
self.finish()
File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
self.wfile.close()
File "/usr/lib/python2.7/socket.py", line 283, in close
self.flush()
File "/usr/lib/python2.7/socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

----------------------------------------
2018-03-15 23:04:56 - Alle Suchfunktion gestartet.
2018-03-15 23:06:09 - Alle Suchfunktion ausgeführt (Dauer: 1.2 Minuten)!
```

- **Genutzte Version** (kein Support für alte Releases)
v.4.0.7

# Fehlerbeschreibung:
nach dieser Fehlermeldung `Exception happened during processing of request from ('192.168.1.201', 55377)` ist das Webinterface nicht mehr erreichbar für mich.

**Comment by DaLeberkasPepi** [comment]
und ist das normal das im docker 2 RSScrawler.py instancen laufen?
```
Mem: 32648124K used, 314880K free, 604204K shrd, 1332K buff, 24211152K cached
CPU:   1% usr   0% sys   0% nic  98% idle   0% io   0% irq   0% sirq
Load average: 2.09 1.96 2.56 2/2065 271
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  240   222 abc      S     173m   1%   0   0% python -u /config/RSScrawler.py --
  222   219 abc      S     139m   0%   8   0% python -u /config/RSScrawler.py --
  258     0 root     S     6348   0%  15   0% /bin/bash
  271   258 root     R     1520   0%  10   0% top
    1     0 root     S      196   0%  11   0% s6-svscan -t0 /var/run/s6/services
   32     1 root     S      196   0%  14   0% s6-supervise s6-fdholderd
  219     1 root     S      196   0%  12   0% s6-supervise rsscrawler
  239   222 abc      DW       0   0%   0   0% [python]
```

**Comment by rix1337** [comment]
Das mehrere Prozesse laufen, sollte kein Problem sein, RSScrawler läuft in mehreren Threads.

Du sendest anscheinend zu viele Requests gleichzeitig per Webinterface ab.
https://stackoverflow.com/questions/43893208/flask-gives-error-32-broken-pipe-when-being-requested-too-often

https://github.com/rix1337/RSScrawler/commit/4a34e5d0f6be7ed4af193b51297b1f89370c8978
Sollte hoffentlich helfen..

**Comment by rix1337** [comment]
Hatte das selbe Problem nach dem Upgrade auf Unraid 6.5.0

**Comment by DaLeberkasPepi** [comment]
Vielen Dank für den schnellen fix! 
Mhm vielleicht ein Prozess von Chrome der die ganze Zeit aktualisieren will.
Hast du einen Tipp was ich im Container für einen Prozess killen muss damit ich den Container in unraid stoppen kann? Der hängt sich immer auf beim stoppen und dann bleibt mir nur ein hard reset

**Comment by rix1337** [comment]
Mir hat nur `reboot` per SSH geholfen.

**Comment by rix1337** [comment]
Das Problem ist, dass Flask nicht für hardcore-Webanwendungen gedacht ist... Hoffen wir mal, dass threading hilft

**Comment by DaLeberkasPepi** [comment]
OK vielen Dank dafür. Grundsätzlich hab ich ja kein Problem mit dem Neustarten, es ist halt immer doof wenn gerade 3 Leute über plex schauen und des eine Mischung von Tag und nachtaktiven sind  :smiley:
