### ISSUE TITLE
Fehler beim Update von 4.2.0 auf 4.2.1

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#196]
Beim Update von 4.2.0 auf 4.2.1 auf meinem Rasperry Pi 3 (Raspbian/Debian Stretch) wirft die setup.sh eine Reihe von Fehlern aus:

```
root@raspi3 /opt > ./setup.sh
┌────────────────────────────────────────────────────────┐
  Programminfo:    RSScrawler v.4.2.1 von RiX
  Projektseite:    https://github.com/rix1337/RSScrawler
└────────────────────────────────────────────────────────┘
Hinweise im Wiki: https://github.com/rix1337/RSScrawler/wiki
Bitte Plattform wählen:
1) Ubuntu/Debian
2) Synology
3) Update
4) Beenden
#? 3
Wo ist RSScrawler installiert? Pfad ohne / am Ende: /opt/RSScrawler
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 487, in _prepare_file req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 428, in _check_skip_installed req_to_install, upgrade_allowed)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
Fordere an von origin
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 24 (delta 15), reused 24 (delta 15), pack-reused 0
Entpacke Objekte: 100% (24/24), Fertig.
Von https://github.com/rix1337/RSScrawler
   cdc1885..733132e  master     -> origin/master
 * [neues Tag]       v.4.2.1    -> v.4.2.1
Fordere an von rss
Von https://github.com/rix1337/RSScrawler
   cdc1885..733132e  master     -> rss/master
HEAD ist jetzt bei 733132e Bugfix
Von https://github.com/rix1337/RSScrawler
 * branch            master     -> FETCH_HEAD
Bereits aktuell.
```

Am Ende lässt sich der Crawler aber ohne Fehler starten.

**Comment by rix1337** [comment]
Irgend etwas stimmt mit deinem pip nicht. Die Fehlermeldung hat erstmal nichts mit dem RSScrawler zu tun.

**Comment by jankete** [comment]
Ursache: `www.piwheels.org` down
