### ISSUE TITLE
TypeError in Notification Function

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#234]
Scheinbar hat sich da irgendwo noch ein kleiner TypeError seit der Umstellung auf Python 3.0 eingeschlichen. Sobald er nämlich links findet und die als Notification weiter rausschicken will bekomm ich diese Meldung.

Der Rest funktioniert bis jetzt wunderbar, nur kommen halt gerade keine Benachrichtigungen für die Downloads an

Possible Fix:
https://github.com/rix1337/RSScrawler/blob/c7d0bc2e82370ec0104ed5df60a6e1c64be1f906/rsscrawler/notifiers.py#L85

`auth = base64.encodestring(('%s:' % token).encode()).decode().replace('\n', '') 
`

```
ErrorWarningSystemArrayLogin


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing...
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
┌────────────────────────────────────────────────────────┐
Programminfo: RSScrawler v.5.0.10 von RiX
Projektseite: https://github.com/rix1337/RSScrawler
└────────────────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Docker-Modus: JDownloader-Pfad und Port können nur per Docker-Run angepasst werden!
Nutze das "folderwatch" Unterverzeichnis von "/jd2" für Crawljobs
2018-10-08 00:49:35 - Alle Suchfunktion ausgeführt (Dauer: 38.0 Sekunden)!
2018-10-08 01:00:16 - Alle Suchfunktion ausgeführt (Dauer: 39.9 Sekunden)!
2018-10-08 01:11:07 - Alle Suchfunktion ausgeführt (Dauer: 50.4 Sekunden)!
2018-10-08 01:21:56 - Alle Suchfunktion ausgeführt (Dauer: 47.9 Sekunden)!
2018-10-08 01:32:45 - Alle Suchfunktion ausgeführt (Dauer: 48.6 Sekunden)!
2018-10-08 01:43:34 - Alle Suchfunktion ausgeführt (Dauer: 48.3 Sekunden)!
2018-10-08 01:54:21 - Alle Suchfunktion ausgeführt (Dauer: 47.2 Sekunden)!
2018-10-08 02:05:10 - Alle Suchfunktion ausgeführt (Dauer: 48.1 Sekunden)!
2018-10-08 02:15:59 - Alle Suchfunktion ausgeführt (Dauer: 48.2 Sekunden)!
2018-10-08 02:26:46 - Alle Suchfunktion ausgeführt (Dauer: 46.2 Sekunden)!
2018-10-08 02:36:47,596 - [DD] - Englisch - [ . . . ]
2018-10-08 02:40:15,910 - [DD] - Englisch - [ . . . ]
2018-10-08 02:41:52,157 - [DD] - Englisch - [ . . . ]
2018-10-08 02:42:43,352 - [DD] - Englisch - [ . . . ]
Traceback (most recent call last):
File "/usr/lib/python3.6/base64.py", line 517, in _input_type_check
m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 145, in crawler
notify(added_items, configfile)
File "/usr/lib/python3.6/site-packages/rsscrawler/notifiers.py", line 51, in notify
Pushbullet(items, pushbullet_token)
File "/usr/lib/python3.6/site-packages/rsscrawler/notifiers.py", line 85, in Pushbullet
auth = base64.encodestring('%s:' % token).replace('\n', '')
File "/usr/lib/python3.6/base64.py", line 547, in encodestring
return encodebytes(s)
File "/usr/lib/python3.6/base64.py", line 534, in encodebytes
_input_type_check(s)
File "/usr/lib/python3.6/base64.py", line 520, in _input_type_check
raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
Traceback (most recent call last):
File "/usr/lib/python3.6/base64.py", line 517, in _input_type_check
m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

[ . . . ]
```

**Comment by rix1337** [comment]
Hi,

ist bisher nicht aufgefallen, da ich Pushover nutze.
Wenn du die Zeit hast, teste deinen Vorschlag
`auth = base64.encodestring(('%s:' % token).encode()).decode().replace('\n', '')`
auf Python 2.7 und 3.5+ und schick mir einen Pull Request.

Dann füge ich das ein.
