### ISSUE TITLE
Error occurred during loading data

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#240]
Folgender Fehler ist gerade mit der Version https://github.com/rix1337/RSScrawler/tree/v.5.0.13 aufgetreten.

```
2018-10-12 04:01:24,481 - Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/usr/lib/python3.6/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/usr/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by rix1337** [comment]
Bitte stell deine db und ini zur Verfügung.

**Comment by rix1337** [comment]
Habe ein paar eher kosmetische bugs (siehe PEP8) gefixt. Sollte dein Fehler ein der 5.0.14 weiter auftreten gibt nochmal mit RSScrawler.db und RSScrawler.ini Bescheid.

**Comment by rix1337** [comment]
Und die exception aus deiner Fehlermeldung wurde eingefangen.

**Comment by DaLeberkasPepi** [comment]
Nicht umbedingt sicher ob das mit dem Problem von vorher zusammen hängt aber mit der neuesten Version bekomme ich eine Menge an Fehler. 
Ich kann leider nicht sagen ab wann die aufgetaucht sind weil das letzte mal wo ich in die Logs gesehen habe war ich noch auf 5.0.13

db/ini und logs files:
[rsscrawler.zip](https://github.com/rix1337/RSScrawler/files/2476910/rsscrawler.zip)

```
[services.d] starting services
[services.d] done.
┌────────────────────────────────────────────────────────┐
Programminfo: RSScrawler v.5.1.2 von RiX
Projektseite: https://github.com/rix1337/RSScrawler
└────────────────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Docker-Modus: JDownloader-Pfad und Port können nur per Docker-Run angepasst werden!
Nutze das "folderwatch" Unterverzeichnis von "/jd2" für Crawljobs
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib/python3.6/http/client.py", line 1239, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
self.send(msg)
File "/usr/lib/python3.6/http/client.py", line 964, in send
self.connect()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
conn = self._new_conn()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
self, "Failed to establish a new connection: %s" % e)

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x14a24ad3c9b0>: Failed to establish a new connection: [Errno -3] Try again


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
timeout=timeout
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='movie-blog.org', port=80): Max retries exceeded with url: /feed/?paged=5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14a24ad3c9b0>: Failed to establish a new connection: [Errno -3] Try again',))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 137, in crawler
task.periodical_task()
File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 1831, in periodical_task
mb_parsed_url = feedparser.parse(get_url(url, configfile, dbfile))
File "/usr/lib/python3.6/site-packages/rsscrawler/url.py", line 78, in get_url
return scraper.get(url, headers={'User-Agent': agent}, timeout=30).text
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
return self.request('GET', url, **kwargs)
File "/usr/lib/python3.6/site-packages/cfscrape/__init__.py", line 64, in request
resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='movie-blog.org', port=80): Max retries exceeded with url: /feed/?paged=5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14a24ad3c9b0>: Failed to establish a new connection: [Errno -3] Try again',))

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib/python3.6/http/client.py", line 1239, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
self.send(msg)
File "/usr/lib/python3.6/http/client.py", line 964, in send
self.connect()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
conn = self._new_conn()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
self, "Failed to establish a new connection: %s" % e)

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x14a24ac59f28>: Failed to establish a new connection: [Errno -3] Try again


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
timeout=timeout
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='movie-blog.org', port=80): Max retries exceeded with url: /feed/?paged=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14a24ac59f28>: Failed to establish a new connection: [Errno -3] Try again',))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 137, in crawler
task.periodical_task()
File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 1831, in periodical_task
mb_parsed_url = feedparser.parse(get_url(url, configfile, dbfile))
File "/usr/lib/python3.6/site-packages/rsscrawler/url.py", line 78, in get_url
return scraper.get(url, headers={'User-Agent': agent}, timeout=30).text
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
return self.request('GET', url, **kwargs)
File "/usr/lib/python3.6/site-packages/cfscrape/__init__.py", line 64, in request
resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='movie-blog.org', port=80): Max retries exceeded with url: /feed/?paged=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14a24ac59f28>: Failed to establish a new connection: [Errno -3] Try again',))

2018-10-14 23:44:36 - Alle Suchfunktion ausgeführt (Dauer: 2.7 Minuten)! Warte 681 Sekunden.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing...
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
```

**Comment by rix1337** [comment]
Dort war eindeutig der MB nicht erreichbar.
