### ISSUE TITLE
Attribute Error seit Version 5.2.1

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#251]
Hab folgende Meldung im Log seit 5.2.1

AttributeError: 'module' object has no attribute 'JSONDecodeError'
    except json.JSONDecodeError:
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 1091, in request_api
    action_url, api)
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 753, in action
    resp = self.device.action(self.url + "/getCurrentState")
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 214, in get_current_state
    downloader_state = device.downloadcontroller.get_current_state()
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjd.py", line 245, in get_info
    myjd = get_info(configfile, device)
  File "/usr/lib/python2.7/site-packages/rsscrawler/web.py", line 421, in myjd_info
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
Traceback (most recent call last):
2018-10-31 12:01:47,800 - Exception on /api/myjd/ [GET]
AttributeError: 'module' object has no attribute 'JSONDecodeError'
    except json.JSONDecodeError:
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 1091, in request_api
    action_url, api)
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 753, in action
    resp = self.device.action(self.url + "/getCurrentState")
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 214, in get_current_state
    downloader_state = device.downloadcontroller.get_current_state()
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjd.py", line 245, in get_info
    myjd = get_info(configfile, device)
  File "/usr/lib/python2.7/site-packages/rsscrawler/web.py", line 421, in myjd_info
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
Traceback (most recent call last):
2018-10-31 12:01:36,932 - Exception on /api/myjd/ [GET]
AttributeError: 'module' object has no attribute 'JSONDecodeError'
    except json.JSONDecodeError:
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 1091, in request_api
    action_url, api)
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 753, in action
    resp = self.device.action(self.url + "/getCurrentState")
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 214, in get_current_state
    downloader_state = device.downloadcontroller.get_current_state()
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjd.py", line 245, in get_info
    myjd = get_info(configfile, device)
  File "/usr/lib/python2.7/site-packages/rsscrawler/web.py", line 421, in myjd_info
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
Traceback (most recent call last):
2018-10-31 12:01:27,002 - Exception on /api/myjd/ [GET]
AttributeError: 'module' object has no attribute 'JSONDecodeError'
    except json.JSONDecodeError:
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 1091, in request_api
    action_url, api)
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 753, in action
    resp = self.device.action(self.url + "/getCurrentState")
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjdapi.py", line 214, in get_current_state
    downloader_state = device.downloadcontroller.get_current_state()
  File "/usr/lib/python2.7/site-packages/rsscrawler/myjd.py", line 245, in get_info
    myjd = get_info(configfile, device)
  File "/usr/lib/python2.7/site-packages/rsscrawler/web.py", line 421, in myjd_info
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
Traceback (most recent call last):
2018-10-31 12:01:19,344 - Exception on /api/myjd/ [GET]

**Comment by DKeppi** [comment]
Ach ja, ich verwende python 2.7!

**Comment by rix1337** [comment]
Ist ein Fehler in der myjdapi.py. Behoben in v5.2.3

**Comment by DKeppi** [comment]
Alles klar danke! :)

**Comment by rix1337** [comment]
Danke für die Fehlermeldung.

Der Umbau mit v.5.2 ist massiv. Gerne alles genau im Auge halten.

**Comment by rix1337** [comment]
Vielen Dank. 👍 

Der Code wird langsam wirklich gut,.. kein Vergleich zu 2016 😉
