### ISSUE TITLE
Fehler, falls My JDownloader keine URL zu Paketen im Downloader/Linkgrabber liefert

### ISSUE THREAD

**Issue by rix1337** [rix1337/RSScrawler#258]
### Lösungsansatz:

Alle `.join` Funktionen in eine `if` Prüfung einwickeln.

```

### Fehlermeldung:
Exception on /api/myjd/ [GET]
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 421, in myjd_info
myjd = get_info(configfile, device)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 260, in get_info
packages_in_downloader = get_packages_in_downloader(device)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 123, in get_packages_in_downloader
urls = "\n".join(urls)
TypeError: sequence item 0: expected str instance, NoneType found
Exception on /api/myjd/ [GET]
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 421, in myjd_info
myjd = get_info(configfile, device)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 260, in get_info
packages_in_downloader = get_packages_in_downloader(device)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 123, in get_packages_in_downloader
urls = "\n".join(urls)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by Slomo17** [comment]
Wollte gestern abend mal die Anbindung an MyJdownloader testen und bekomme genau die gleiche Fehlermeldung

**Comment by rix1337** [comment]
Putzig, bei mir läuft es mit zwei verschiedenen Testgeräten, aber den Grund für die Fehlermeldung werde ich beheben. Danke für die Info

**Comment by Slomo17** [comment]
Das ging ja schnell, danke, allerdings bekomme ich die Fehlermeldung weiterhin und in der Weboberfläche steht weiterhin: "Keine Zugangsdaten für My JDownloader gefunden." obwohl die Zugangsdaten eingetragen und richtig sind. Mache ich etwas falsch?

Hier noch mal meine genaue Ausgabe:

```
┌──────────────────────────────────────────────┐
  RSScrawler v.5.2.7 von RiX
  https://github.com/rix1337/RSScrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /home/tobi/Scripts/rsscrawlerconfig für Einstellungen/Logs
Erfolgreich mit My JDownloader verbunden. Gerätename: Server
Der Webserver ist erreichbar unter http://192.168.188.91:7777
Drücke [Strg] + [C] zum Beenden
2018-11-01 23:30:59 - Alle Suchfunktion ausgeführt (Dauer: 0.08s)! Wartezeit bis zum nächsten Suchlauf: 11m:30s
Exception on /api/myjd/ [GET]
Traceback (most recent call last):
  File "/home/tobi/.local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tobi/.local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tobi/.local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tobi/.local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/tobi/.local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tobi/.local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tobi/.local/lib/python3.7/site-packages/rsscrawler/web.py", line 421, in myjd_info
    myjd = get_info(configfile, device)
  File "/home/tobi/.local/lib/python3.7/site-packages/rsscrawler/myjd.py", line 267, in get_info
    packages_in_downloader = get_packages_in_downloader(device)
  File "/home/tobi/.local/lib/python3.7/site-packages/rsscrawler/myjd.py", line 127, in get_packages_in_downloader
    urls = "\n".join(urls)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by Slomo17** [comment]
Cool, jetzt funktioniert es, vielen Dank :)

**Comment by rix1337** [comment]
Gerne. Nur aus interesse. Was für ein Paket lag bei dir im Jdownloader rum?

Die Fehlermeldung sagt, dass du Pakete ohne Url dort liegen hast.. was eigentlich nicht gehen sollte.
Vielleicht kann ich deinen Fall noch intelligenter abfangen.

**Comment by Slomo17** [comment]
Hm gute Frage, ich hatte recht viel in der Warteschlange, ein teil bei denen die Datein nicht mehr vorhanden waren, vielleicht war das das Problem:
![jdownloader](https://user-images.githubusercontent.com/14056946/47956169-b5a43880-dfa0-11e8-9796-cd161d8cc3e7.png)

**Comment by rix1337** [comment]
Alles klar, danke für die Info. In dem Fall ist das aktuelle Vorgehen schon ausreichend.
