### ISSUE TITLE
FakeUserAgentError

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#262]
Folgendes stand heute früh im Log:

‘‘‘FakeUserAgentError: Maximum amount of retries reached
    raise FakeUserAgentError('Maximum amount of retries reached')
  File "/usr/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get
    verify_ssl=verify_ssl,
  File "/usr/lib/python2.7/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/usr/lib/python2.7/site-packages/fake_useragent/utils.py", line 166, in load
Traceback (most recent call last):
2018-11-02 17:10:18,486 - Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11‘‘‘

**Comment by rix1337** [comment]
Liegt an fakeuseragent. Das Issue dort wurde bisher nicht behoben.
https://github.com/hellysmile/fake-useragent/issues/78

**Comment by DKeppi** [comment]
Alles klar...danke! 😉

**Comment by rix1337** [comment]
Den auf fakeuseragent bezogenen. Ja.

**Comment by DaLeberkasPepi** [comment]
Des mit dem MB Fehler ist mir auch noch ein Rätsel. Wie ich es per Hand probiert habe hat es mit dem link ohne Probleme funktioniert. Ist es eventuell ein Problem wenn er zu schnell sucht das er geblockt wird vom MB Server?

**Comment by rix1337** [comment]
Gute frage, den habe ich so noch nicht gesehen.

Kann alle möglichen gründe haben. Solange der nicht nachvollziehbar in jedem Suchlauf kommt, war es vermutlich das Netzwerk (deins oder das von MB)

**Comment by rix1337** [comment]
Dort tut sich nichts...
