### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#269]
Hab gerade den neuen Docker Container auf der Synology probiert, so bin ich nicht vom Synology Python abhängig und es würde einiges erleichtern!
Läuft nun endlich, aber im Log habe ich einen Fehler, oder liegt das daran dass ich den JD2 Login noch nicht eingetragen habe?

```
TypeError: 'bool' object is not subscriptable
    device = myjd[0]
  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 434, in myjd_info
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    raise value
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
Traceback (most recent call last):
2018-11-13 07:39:36,006 - Exception on /api/myjd/ [GET]
```

**Comment by rix1337** [comment]
Nö, ist ein Fehler. Der sollte allerdings nicht auftreten, wenn die My JDownloader Verbindung funktioniert hat.

**Comment by rix1337** [comment]
Beheben in: 
https://github.com/rix1337/RSScrawler/blob/3809207fe618415f5a6174fa50a6c146a4a87003/rsscrawler
/web.py#L434

**Comment by DKeppi** [comment]
Stimmt ja, dann ist er weg! ;)
Alles klar, danke!

**Comment by rix1337** [comment]
Danke für die Meldung, wird im nächsten Release behoben.
