### ISSUE TITLE
Endlosschleife mit Ombi

### ISSUE THREAD

**Issue by RealJustMe** [rix1337/RSScrawler#290]
Hi, wenn ein Film durch Ombi hinzugefügt wird geht es in eine endlos schleife. Der Film wird immer und immer wieder hinzugefügt.

┌──────────────────────────────────────────────┐
  RSScrawler v.5.4.2 von RiX
  https://github.com/rix1337/RSScrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis ***** für Einstellungen/Logs
Erfolgreich mit My JDownloader verbunden. Gerätename: *****
Der Webserver ist erreichbar unter *****
Drücke [Strg] + [C] zum Beenden
--------Alle Suchfunktion gestartet.--------
Kein Retail-Release für die Suche nach Bomb City gefunden! Suchliste ergänzt.
Film: Bomb City durch Ombi hinzugefügt.
[Suche/Film] - Englisch - Bomb.City.2017.720p.BluRay.X264-AMIABLE
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/RSScrawler.py", line 113, in crawler
    device = ombi(configfile, dbfile, device, log_debug)
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/ombi.py", line 136, in ombi
    search.download_bl(best_result, device, configfile, dbfile)
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/search.py", line 502, in download_bl
    notify([log_entry], configfile)
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/notifiers.py", line 65, in notify
    pushbullet(items, pushbullet_token)
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/notifiers.py", line 114, in pushbullet
    res = json.load(response)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
--------Alle Suchfunktion gestartet.--------

**Comment by rix1337** [comment]
Danke für die Meldung.
Schau ich mir bei Zeiten an (kann bis März dauern). Bis dahin, nimm Pushbullet aus deinen Einstellungen raus - dann sollte zumindest der Crawler laufen.

Es fehlen noch infos zum genutzten System, um den Fehler nachzustellen

**Comment by RealJustMe** [comment]
Ah mist die wollte ich eben noch anhängen:
1. RPi3 mit Dietpi und python v3.5.3
2. Xubuntu 18.04 (32bit) mit python v3.6.7

brauchst du sonst noch was?

Ohne Pushbullet klappts super also lass dir ruhig zeit :D

**Comment by rix1337** [comment]
Der Fehler kommt aus der json-Bibliothek..

versuch mal zuerst simplejson zu installieren (https://pypi.org/project/simplejson/) .. vielleicht klappt es damit

**Comment by RealJustMe** [comment]
Läuft doch nicht so ganz.

--------Alle Suchfunktion gestartet.--------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/RSScrawler.py", line 113, in crawler
    device = ombi(configfile, dbfile, device, log_debug)
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/ombi.py", line 133, in ombi
    best_result = search.best_result_bl(title, configfile, dbfile)
  File "/usr/local/lib/python3.5/dist-packages/rsscrawler/search.py", line 271, in best_result_bl
    best_title):
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
--------Alle Suchfunktion gestartet.--------

Das kommt nachdem die Filme hinzugefügt worden sind. Auch wieder in endlosschleife. Denke mal da geht er zu den Serien über?

Mit simplejason geht zumindest Pushbullet wieder aber der selbe fehler.

**Comment by rix1337** [comment]
Okay, irgendwas ist merkwürdig - der decoding fehler sollte unter python 3 nicht auftreten.

Du kannst noch versuchen ob python 2 klappt - aber das muss ich mir insgesamt mal ansehen

**Comment by RealJustMe** [comment]
Ok, hatte gestern abend ein paar schwierigkeiten gehabt es mit python2 zum laufen zu kriegen. war einfach zu spät.

mit python 2.7 bekomme ich folgenden fehler:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rsscrawler/RSScrawler.py", line 113, in crawler
    device = ombi(configfile, dbfile, device, log_debug)
  File "/usr/local/lib/python2.7/dist-packages/rsscrawler/ombi.py", line 133, in ombi
    best_result = search.best_result_bl(title, configfile, dbfile)
  File "/usr/local/lib/python2.7/dist-packages/rsscrawler/search.py", line 279, in best_result_bl
    logging.debug(u'Kein Treffer für die Suche nach ' + title + '! Suchliste ergänzt.')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)

**Comment by rix1337** [comment]
Irgendwas am Raspberry Pi environment sieht ungewöhnlich aus.

Versuchs mal mit `export PYTHONIOENCODING=utf-8` aus der Readme.md

Der Befehl sollte den Fehler verschwinden lassen.

**Comment by RealJustMe** [comment]
Der Fehler bleibt leider genauso bestehen.

Ohne Ombi läuft es mit Python 3 wenigstens.

**Comment by rix1337** [comment]
Konnte es bisher nicht nachstellen
