### ISSUE TITLE
Loginversuche bei MyJDownloader nach Fehlermeldungen drosseln

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#310]
ich weiß es ist nicht wirklich ein echter Fehler aber unschön sieht es trotzdem aus. 
```
┌──────────────────────────────────────────────┐
RSScrawler v.5.6.2 von RiX
https://github.com/rix1337/RSScrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
raise err
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
conn.connect()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
conn = self._new_conn()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
(self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x153cd0cebbe0>, 'Connection to api.jdownloader.org timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.jdownloader.org', port=443): Max retries exceeded with url: /my/listdevices?sessiontoken=e103e5ea788eae8f0bd489cb4e0c98b63ca048b0&rid=1562879394&signature=edeb6c9c7f8726ed57c69d993f3a22ba8aee225a71022a41aeb6b13cd278c43c (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x153cd0cebbe0>, 'Connection to api.jdownloader.org timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/rsscrawler", line 10, in <module>
sys.exit(main())
File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 232, in main
device = get_device(configfile)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 29, in get_device
jd.connect(myjd_user, myjd_pass)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjdapi.py", line 934, in connect
self.update_devices()
File "/usr/lib/python3.6/site-packages/rsscrawler/myjdapi.py", line 980, in update_devices
[("sessiontoken", self.__session_token)])
File "/usr/lib/python3.6/site-packages/rsscrawler/myjdapi.py", line 1059, in request_api
encrypted_response = requests.get(api + query, timeout=3)
File "/usr/lib/python3.6/site-packages/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.jdownloader.org', port=443): Max retries exceeded with url: /my/listdevices?sessiontoken=e103e5ea788eae8f0bd489cb4e0c98b63ca048b0&rid=1562879394&signature=edeb6c9c7f8726ed57c69d993f3a22ba8aee225a71022a41aeb6b13cd278c43c (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x153cd0cebbe0>, 'Connection to api.jdownloader.org timed out. (connect timeout=3)'))
```
Vielleicht ist dir ja einmal langweilig und du baust eine response für zuviele Loginversuche aus und baust einfach einen kleinen Wartetimer ein oder sowas. Aber wie gesagt nichts tragisches

**Comment by rix1337** [comment]
Gute Idee, ich vermute 10 Sekunden sollten reichen
