### ISSUE TITLE
in v.5.6.4 scheint sich noch ein Bug eingeschlichen haben

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#313]
```
TypeError: argument of type 'NoneType' is not iterable
Exception on /api/myjd/ [GET]
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 84, in decorated
return f(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 512, in myjd_info
myjd = get_info(configfile, device)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 282, in get_info
packages_in_linkgrabber = get_packages_in_linkgrabber(device)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 136, in get_packages_in_linkgrabber
packages_by_type = check_packages_types(links, packages)
File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 199, in check_packages_types
'status') or 'An error occurred!' in package.get('status'):
```

**Comment by rix1337** [comment]
Danke für die schnelle Meldung @DaLeberkasPepi 

Habe diesen und einen weiteren Bug gefixt
