### ISSUE TITLE
Fehler bei der manuellen Suche

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#385]
# [RSScrawler] Fehlermeldung

Dieser Bereich dient der Fehlermeldung.

Für Rückfragen und Chat gibt es:
https://gitter.im/RSScrawler/Lobby

# Zwingend erforderlich

- **Fehlermeldung aus dem Log**
```
Exception on /api/search/Parasite 265 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 87, in decorated
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 503, in search_title
    results = search.get(title, configfile, dbfile)
  File "/usr/lib/python3.6/site-packages/rsscrawler/search.py", line 90, in get
    fx_results = fx_search_results(fx_content_to_soup(res))
  File "/usr/lib/python3.6/site-packages/rsscrawler/fakefeed.py", line 184, in fx_search_results
    title = fx_post_title(content)
  File "/usr/lib/python3.6/site-packages/rsscrawler/fakefeed.py", line 194, in fx_post_title
    content = BeautifulSoup(content, 'lxml')
  File "/usr/lib/python3.6/site-packages/bs4/__init__.py", line 322, in __init__
    markup, from_encoding, exclude_encodings=exclude_encodings)):
  File "/usr/lib/python3.6/site-packages/bs4/builder/_lxml.py", line 186, in prepare_markup
    for encoding in detector.encodings:
  File "/usr/lib/python3.6/site-packages/bs4/dammit.py", line 302, in encodings
    self.markup, self.is_html)
  File "/usr/lib/python3.6/site-packages/bs4/dammit.py", line 378, in find_declared_encoding
    declared_encoding_match = xml_re.search(markup, endpos=xml_endpos)
TypeError: expected string or bytes-like object
```

- **Genutzte Version** (kein Support für alte Releases)
6.5.4

- **Wird Python 3.7 oder aktueller genutzt?**
Docker-Image

# Fehlerbeschreibung:

Bei Nutzung der manuellen Suchfunktion erscheint die angegebene Fehlermeldung im Log.

[INI_DB_LOG.zip](https://github.com/rix1337/RSScrawler/files/4274943/INI_DB_LOG.zip)

**Comment by rix1337** [comment]
Interessant, mit deiner DB/INI kommt der Fehler auch bei mir. Sonst nicht.

**Comment by rix1337** [comment]
Gelöst.
